### ISSUE TITLE
/db failed: No such device

### ISSUE THREAD

**Issue by josephwinston** [docker/datakit#104]
I'm on Centos 7 using datakit <https://github.com/docker/datakit/commit/51bcdedbe2f16f8d59cc1dc4fdbfb8d9c8848ffa> and ran in one terminal:

```bash
$ ./scripts/start-datakit.sh
```

After building finished, in another term I ran:

```bash
 datakit-mount
mount: mounting 172.17.0.2 on /db failed: No such device
```

Is this expected behavior?

**Comment by samoht** [comment]
> Is this expected behavior?

Not really :-) I think you forgot to run `$ ./scripts/start-client.sh` in your new terminal.

But as datakit just exposes a normal 9p endpoint, you can just use a normal mount command, for instance:

```
sudo mount -t 9p -o trans=tcp,port=5640,noextend,nodev 127.0.0.1 /mnt/db
```

**Comment by josephwinston** [comment]
I'm hoping it is a user error on my part in reporting the bug.  I thought that I had run ```$ ./scripts/start-client.sh```.  History shows that I did.  Something else is going on.

I don't see any interesting logs.  Where can I look?

**Comment by samoht** [comment]
The `start-client.sh` will start a new container. Please be sure you are running `datakit-mount` in the shell of that container. But it's maybe an issue with the IP of the first container.

 If that's already the case I guess that's an issue with the IP address of the container running Datakit. Can you try to `ping db` to get the right IP address of the DB and use it to all the mount script: `datakit -h <IP>`?

**Comment by samoht** [comment]
I've tried to simplify the "quick start" step. Now the following should work:

```
docker network create datakit-net
docker run -d --net datakit-net --rm -ame datakit docker/datakit
docker run -it --net datakit-net --privileged docker/datakit:client
ls /db
```

Thanks for the feedback and let me know if you have more issues!

**Comment by samoht** [comment]
@josephwinston hopefully the doc is now clearer. I'm going to close that issue now, but please re-open it if you still have issues/questions!
