### ISSUE TITLE
Unix.Unix_error(Unix.EINVAL, "select", "") on Alpine Linux

### ISSUE THREAD

**Issue by talex5** [docker/datakit#152]
Looks like lwt doesn't detect `libev` on Alpine 3.3 and falls back to select mode. Perhaps select mode is buggy (I guess not many people use it)?

**Comment by talex5** [comment]
Probably related to https://github.com/ocsigen/lwt/issues/222.

**Comment by talex5** [comment]
Lwt's `discover.ml` detects libev correctly on Alpine by using `pkg-config`, but it isn't used when building with opam. Instead, that uses `conf-libev`, which doesn't support `pkg-config`.

@avsm is fixing...

**Comment by talex5** [comment]
Workaround: `apk add ncurses-dev`

**Comment by samoht** [comment]
I have a PR doing that #163
