### ISSUE TITLE
datakit-gh triggers on everything

### ISSUE THREAD

**Issue by FrenchBen** [docker/datakit#160]
The `datakit-gh` hook should only listen for Commits made. 
Adding a comment to a PR shouldn't re-trigger a check.

**Comment by samoht** [comment]
I am not sure what you are referring too. You can select the events you send to it (currently PR changes and Status changes) in the webhook interface.

**Comment by samoht** [comment]
After discussing with @FrenchBen, it appears that the PR stream is updated on every modification of the PR (as we match the "last updated" field [there](https://github.com/docker/datakit/blob/master/src/vgithub/vgithub.ml#L25)). It would be better to check for SHA1 changes instead.
