### ISSUE TITLE
Backend for Github API

### ISSUE THREAD

**Issue by samoht** [docker/datakit#19]
This would allow to watch for Github events directly in the 9p filesystem, and interact with PR (can toggle the green tick on successful builds for instance)

**Comment by cviebig** [comment]
Alternatively one could fetch the pull requests directly via git:
```
[remote "origin"]
    url = https://github.com/syl20bnr/spacemacs
    fetch = +refs/heads/*:refs/remotes/origin/*
    fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```
Would this be a more simpler option than interfacing with the API?

**Comment by samoht** [comment]
Yes, also we wanted to be able to toggle the `build` status of the PRs through the filesystem. But thanks for the suggestion!
