### ISSUE TITLE
`DK.Transaction.exists_dir f` is true if `f` is an empty file

### ISSUE THREAD

**Issue by samoht** [docker/datakit#191]
If you create an empty file in a transaction and try to check if it's a directory you get strange results.

**Comment by talex5** [comment]
Well, it appears someone defined them all as:

    let exists t path      = FS.exists t.fs (t.path / "rw" /@ path)
    let exists_file t path = FS.exists t.fs (t.path / "rw" /@ path)
    let exists_dir t path  = FS.exists t.fs (t.path / "rw" /@ path)

**Comment by samoht** [comment]
ha ...

**Comment by talex5** [comment]
Thanks for the fix. BTW, it appears these API additions were made in PR https://github.com/docker/datakit/pull/173, which is titled just "Cleanups", had no other description, and was merged in status/0-triage with no review or unit-tests :-(
