### ISSUE TITLE
GitHub bridge fails to sync closed PRs

### ISSUE THREAD

**Issue by talex5** [docker/datakit#235]
I had an open PR#1 on my virtual test GitHub, which I then closed. After syncing the bridge, the PR is still marked as open on DataKit:

```
GitHub:
{("a",
  {("a",
    prs=[n=0;head=123;title="PR#0";open; n=1;head=789;title="PR#1";closed;
         n=2;head=456;title="PR#2";open; n=3;head=456;title="PR#3";open];
    commits=[123->[[a/a:123:ci/datakit/test, description=Testing..., pending]];
             456->[[a/a:456:ci/datakit/test, description=Testing..., pending]]])
   ("b", prs=[];commits=[])})
 ("b", {("a", prs=[];commits=[]) ("b", prs=[];commits=[])})}
DataKit:
{("a",
  {("a",
    prs=[n=0;head=123;title="PR#0";open; n=1;head=123;title="PR#1";open;
         n=2;head=456;title="PR#2";open; n=3;head=456;title="PR#3";open];
    commits=[123->[[a/a:123:ci/datakit/test, description=Testing..., pending]];
             456->[[a/a:456:ci/datakit/test, description=Testing..., pending]]])
   ("b", prs=[];commits=[])})
 ("b", {("a", prs=[];commits=[]) ("b", prs=[];commits=[])})}
```

Looking at the code, it appears that `import_repos` filters out closed PRs:

https://github.com/docker/datakit/blob/122e3a8e96850089af769e5fffd4ba21327e0712/bridge/github/src/datakit_github.ml#L859

This is then passed to `Conv.update_prs`, which does:

```
    match pr.PR.state with
    | `Closed -> safe_remove t dir
```

https://github.com/docker/datakit/blob/122e3a8e96850089af769e5fffd4ba21327e0712/bridge/github/src/datakit_github.ml#L506

**Comment by samoht** [comment]
Do you have any existing test which reproduce the issue?

**Comment by talex5** [comment]
Yes. Here's the commit with the test: https://github.com/talex5/datakit/commit/10c96584effe7f57681203d4e6018245f199a2f2

Here's the travis output: https://travis-ci.org/talex5/datakit/jobs/154159945 (the random seed is fixed, so you'll get the same result locally too)
