### ISSUE TITLE
Bridge tries to move tags

### ISSUE THREAD

**Issue by talex5** [docker/datakit#275]
Example log message:
```
2016-09-26 15:22 dkt-github [INFO] API.set-ref {docker/my-tag[a08c146ee6cf85e8634aa3e1745dbdb2707a5b67]}
2016-09-26 15:22 dkt-github [ERROR] error: (Failure "not implemented")
```

@samoht says:
> I think I’ve fixed the tags when importing the references on startup, not when receiving webhook events

**Comment by talex5** [comment]
Perhaps we should have a policy file that says what the bridge is allowed to update. Then we could automatically abort/log an error if it tries to do anything else (e.g. change a title, move a tag, update DataKitCI's status, etc).

**Comment by samoht** [comment]
Yes, I've added such policy in #279 so you can do `datakit-github --cap *:r,status:rw` to allow the read of all objects and write of build status only.

**Comment by samoht** [comment]
> Then we could automatically abort/log an error if it tries to do anything else 

currently I just pretend the call worked and skip the actual call when the bridge tries to do something that it is not allowed to do. Would be better to display the policy breach more pro-eminently in the logs.

**Comment by samoht** [comment]
The bridge will now prints an info message when an operation is denied, so closing.
