### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by talex5** [docker/datakit#301]
The `opam` file says:

```
license: "ISC"
```

but the `README.md` file says:

```
DataKit is licensed under the Apache License, Version 2.0. See LICENSE for the full license text.
```

`LICENSE` is a broken link.

**Comment by talex5** [comment]
@samoht what should it be?

**Comment by samoht** [comment]
It should be Apache for everything. Thanks for noticing, I'll fix it ASAP
