### ISSUE TITLE
Increase the errors/warnings verbose

### ISSUE THREAD

**Issue by rogaha** [docker/datakit#364]
Currently we are not able to track down issues related to `datakit` from the upstream services.

**Comment by samoht** [comment]
Can you be more specific? Which message to you want to see?

You can use `-v` or `-vv` to be more verbose.

**Comment by rogaha** [comment]
@samoht I'll add more information on the other repo, maybe it cab be configured on the parent `service`.

**Comment by samoht** [comment]
After discussion it appears that it should be fixed by 629d705d06b867fdadc8d1ef5a672d9930d8bae3
