### ISSUE TITLE
Where can we talk?

### ISSUE THREAD

**Issue by alexisvincent** [docker/datakit#423]
@talex5 I'm wanting to build a layered file system git-like thing. I noticed this project and would very much like to speak to you. Do you hangout on an IM? Slack or Gitter maybe?

**Comment by talex5** [comment]
https://dockercommunity.slack.com/messages/docker-storage/ is probably the best place to discuss DataKit.

**Comment by thaJeztah** [comment]
See this blog post if you have not registered yet; https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/
