### ISSUE TITLE
`--listen-prometheus` is not in the right man section

### ISSUE THREAD

**Issue by samoht** [docker/datakit#475]
e.g. `datakit-github --help` displays:

```
OPTIONS

 --listen-prometheus=VAL
           Port on which to provide Prometheus metrics over HTTP, of the form
           port or host:port
```

it should be in the `LISTEN OPTIONS` section.

**Comment by talex5** [comment]
I'll move it to its own "MONITORING" section. That way, it can be in the same place for all applications.
