### ISSUE TITLE
documentation for using a local git repository with the ci

### ISSUE THREAD

**Issue by hannesm** [docker/datakit#509]
I fail to find any documentation how to setup datakit-ci with a local git repository using irmin-watcher (is the `README.md` in the ci subdirectory still up to date?), but I heard this should be possible somehow...

Is there any plan to extend the API documentation (see https://docker.github.io/datakit/Datakit_ci.html), and how stable is the API (any planned revisions)?  Any chance there will be a release which works with mirage-3.0 and irmin-1.0?

**Comment by talex5** [comment]
The documentation at https://github.com/docker/datakit/blob/master/ci/self-ci/README.md should show how to use a local repository, although it does assume you're using Docker.

If not, the steps are roughly:

1. Run `datakit -v` (this will be in-memory only, just for testing)
2. Run `datakit-bridge-local-git -v me/my-project:/path/to/local/repo`
3. Run CI (configured to test `me/my-project`).

Looks like @samoht added that `TODO` in the docs, but I'm not sure what he's planning to write there.

There's an introduction at https://github.com/docker/datakit/blob/master/ci/README.md which might be useful.

Is there anything you particularly want to see?

@samoht is working on Irmin 1.0 support.

**Comment by samoht** [comment]
@talex5 for the docs, I think it would be great to give a high-level explanation of the library in the `.mli` plus some examples. The API is great but maybe a bit difficult to grasp with the current level of explanations.

**Comment by hannesm** [comment]
@talex5 I particularly want to see the most simple setup (which means: least amount of software pieces involved so that I can try to comprehend which pieces are playing how together) I can locally use.  This may be your 3 steps above (thanks for providing these, I'll try it out), although I'm unsure what `Run CI (configured to test me/my-project)` means (in terms of shell commands).  What does the `me/my-project:/path/to/local/repo` do?  Introducing a new `me/my-project` name?

The "introduction" you point to is how to setup datakit with github bridge etc.  Every time I read through it, I get even more confused.

In terms of API docs I linked to above, they don't look very complete, and what @samoht suggests - high-level explanation of the various parts, together with some examples - would be really nice to have.

Thanks!

**Comment by hannesm** [comment]
slowly getting something again into shape here

**Comment by hannesm** [comment]
nevermind, I use shell scripts now.
