### ISSUE TITLE
Use Datakit as CI for Moby

### ISSUE THREAD

**Issue by talex5** [docker/datakit#70]
Current status:
- Builds alpine/kernel OK
- Builds lots of packages
- Fails cloning docker repository

```
Cloning into 'docker.git'...
error: Unable to create /database/branch/initrd-of-5da84d3c468a6ee03d550e74b58bba9439e362a8/transactions/log/rw/alpine/packages/docker/docker.git/.git/HEAD
```

The immediate issue is that we don't support rename in transactions. However, running Git inside a transaction is probably a bad idea anyway (will need cross-directory rename sooner or later, which 9p doesn't support).

Ideally, I think we want to handle cloning of repositories inside Datakit itself (which would be more efficient than downloading the whole thing on every build). However, a short-term fix would be to clone the repository into /tmp or similar.

**Comment by samoht** [comment]
Closing this one as I believe it now works properly.
