### ISSUE TITLE
Go interface

### ISSUE THREAD

**Issue by samoht** [docker/datakit#8]
Raw-9p is quite a low-level interface to the DB. We should design a higher-level Go interface. An interface is already there in [pinata](https://github.com/docker/pinata/tree/master/v1/abstractions) and variious discussion have been taken place about that in the past:
- support for trim and bind https://github.com/docker/pinata/issues/9
- nicer FS interface https://github.com/docker/pinata/issues/87

**Comment by samoht** [comment]
@djs55 did you made any progress on that? I had a quick look at porting our existing bindings, I can finish that later this week if you want.

**Comment by djs55** [comment]
I've not done any work in them recently. If you do move them into the
datakit tree, I think you should take or write some examples too, so people
can see how they're meant to be used and how they could be made better
(otherwise they might seem a little arbitrary)

**Comment by samoht** [comment]
Closing as we now have https://github.com/docker/datakit/tree/master/api/go-datakit

These bindings are pretty basic but sufficient to interact with Datakit and are used in production in Docker for Mac and Windows.
